#@follow_tag(brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_golang_1.23)
FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:v1.23.6-202503041452.g6707acc.el8 AS builder
COPY $REMOTE_SOURCES $REMOTE_SOURCES_DIR
WORKDIR $REMOTE_SOURCES_DIR/rsync-transfer/app
ENV GOEXPERIMENT strictfipsruntime
ENV BUILDTAGS containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp exclude_graphdriver_overlay strictfipsruntime
RUN source /remote-source/rsync-transfer/cachito.env && GOMODCACHE=/remote-source/rsync-transfer/deps/gomod/pkg/mod GO111MODULE=auto CGO_ENABLED=1 GOOS=linux go build -mod=readonly -v -installsuffix "static" -tags "$BUILDTAGS" -o _output/blockrsync ./cmd/blockrsync/main.go
RUN source /remote-source/rsync-transfer/cachito.env && GOMODCACHE=/remote-source/rsync-transfer/deps/gomod/pkg/mod GO111MODULE=auto CGO_ENABLED=1 GOOS=linux go build -mod=readonly -v -installsuffix "static" -tags "$BUILDTAGS" -o _output/proxy ./cmd/proxy/main.go

#@follow_tag(registry.redhat.io/ubi8/ubi-minimal)
FROM registry.redhat.io/ubi8/ubi-minimal:8.10-1255
RUN microdnf -y install openssh-server stunnel rsync nmap && microdnf clean all

COPY --from=builder $REMOTE_SOURCES_DIR/rsync-transfer/app/_output/blockrsync /blockrsync
COPY --from=builder $REMOTE_SOURCES_DIR/rsync-transfer/app/_output/proxy /proxy

COPY $REMOTE_SOURCES/rsync-transfer/app/sshd_config /etc/ssh/sshd_config
COPY $REMOTE_SOURCES/rsync-transfer/app/stunnel.conf /etc/stunnel/stunnel.conf

USER 65534:65534
WORKDIR /

LABEL \
        com.redhat.component="openshift-migration-rsync-transfer-container" \
        version="v1.8.7" \
        name="rhmtc/openshift-migration-rsync-transfer" \
        summary="Migration Toolkit for Containers Rsync Transfer" \
        maintainer="Migration Team <ocp-migrate-team@redhat.com>" \
        License="ASL 2.0" \
        io.k8s.display-name="Migration Toolkit for Containers" \
        io.openshift.tags="migration" \
        io.k8s.description="Migration Toolkit for Containers Rsync Transfer" \
        io.openshift.build.commit.id="1d6bc70d88599a7a511c6e37524f9125502a3380" \
        io.openshift.build.source-location="https://github.com/migtools/rsync-transfer" \
        io.openshift.build.commit.url="https://github.com/migtools/rsync-transfer/commit/1d6bc70d88599a7a511c6e37524f9125502a3380"
